# Generated by Django 4.2.27 on 2025-12-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLocation', models.CharField(max_length=100, verbose_name='Počiatočný bod')),
                ('endLocation', models.CharField(max_length=20, verbose_name='Koncový bod')),
            ],
            options={
                'verbose_name': 'Obľúbená trasa',
                'verbose_name_plural': 'Obľúbené trasy',
            },
        ),
    ]
