# Generated by Django 4.2.27 on 2025-12-04 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Používateľ'),
        ),
        migrations.AlterUniqueTogether(
            name='favouriteroute',
            unique_together={('user', 'startLocation', 'endLocation')},
        ),
    ]
