# Generated by Django 4.2.27 on 2026-01-07 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='číslo alebo názov linky')),
            ],
            options={
                'verbose_name': 'Linka',
                'verbose_name_plural': 'Linky',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Názov zastávky')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Poloha')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Zemepisná šírka')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Zemepisná dĺžka')),
            ],
            options={
                'verbose_name': 'Zastávka',
                'verbose_name_plural': 'Zastávky',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='ŠPZ / Evidenčné číslo')),
                ('vehicle_type', models.CharField(choices=[('bus', 'Autobus'), ('tram', 'Električka'), ('trolleybus', 'Trolejbus')], max_length=20, verbose_name='Typ vozidla')),
                ('capacity', models.IntegerField(verbose_name='Kapacita cestujúcich')),
            ],
            options={
                'verbose_name': 'Vozidlo',
                'verbose_name_plural': 'Vozidlá',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField(verbose_name='čas odchodu')),
                ('arrival_time', models.TimeField(verbose_name='čas príchodu')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.route', verbose_name='Linka')),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.vehicle', verbose_name='Priradené vozidlo')),
            ],
            options={
                'verbose_name': 'Spoj',
                'verbose_name_plural': 'Spoje',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='end_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_ending', to='data_management.stop', verbose_name='Koncová zastávka'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting', to='data_management.stop', verbose_name='Začiatočná zastávka'),
        ),
    ]
