# Generated by Django 4.2.27 on 2026-01-05 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='číslo alebo názov linky')),
                ('type', models.CharField(choices=[('bus', 'Autobus'), ('trolley', 'Trolejbus'), ('tram', 'Električka')], max_length=10, verbose_name='Typ dopravy')),
            ],
            options={
                'verbose_name': 'Linka',
                'verbose_name_plural': 'Linky',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Názov zastávky')),
                ('latitude', models.FloatField(verbose_name='Zemepisná šírka')),
                ('longitude', models.FloatField(verbose_name='Zemepisná dĺžka')),
            ],
            options={
                'verbose_name': 'Zastávka',
                'verbose_name_plural': 'Zastávky',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='ŠPZ / Evidenčné číslo')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapacita cestujúcich')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model vozidla')),
            ],
            options={
                'verbose_name': 'Vozidlo',
                'verbose_name_plural': 'Vozidlá',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departureTime', models.DateTimeField(verbose_name='čas odchodu')),
                ('arrivalTime', models.DateTimeField(verbose_name='čas príchodu')),
                ('endStopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_end', to='data_management.stop', verbose_name='Koncová zastávka')),
                ('routeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.route', verbose_name='Linka')),
                ('startStopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_start', to='data_management.stop', verbose_name='Začiatočná zastávka')),
                ('vehicleID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.vehicle', verbose_name='Priradené vozidlo')),
            ],
            options={
                'verbose_name': 'Spoj',
                'verbose_name_plural': 'Spoje',
            },
        ),
    ]
