# Generated by Django 4.2.27 on 2025-12-16 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='ŠPZ / Evidenčné číslo')),
                ('capacity', models.PositiveIntegerField(verbose_name='Kapacita cestujúcich')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model vozidla')),
            ],
            options={
                'verbose_name': 'Vozidlo',
                'verbose_name_plural': 'Vozidlá',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicleID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_management.vehicle', verbose_name='Priradené vozidlo'),
        ),
    ]
