# Generated by Django 4.2.27 on 2026-01-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_alter_route_options_alter_stop_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='location',
        ),
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(default=48.7, verbose_name='Zemepisná šírka'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Zemepisná dĺžka'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='data_management.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.stop')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('route', 'stop')},
            },
        ),
    ]
