# Generated by Django 4.2.27 on 2026-01-17 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_remove_stop_location_alter_stop_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['order'], 'verbose_name': 'Zastávka na linke', 'verbose_name_plural': 'Zastávky na linke'},
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Poradie'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='data_management.route', verbose_name='Linka'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_management.stop', verbose_name='Zastávka'),
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'order')},
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop'), name='unique_stop_per_route'),
        ),
    ]
