# Generated by Django 4.2.27 on 2026-02-08 18:48

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_remove_routestop_unique_stop_per_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizovaná'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvorený'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizovaný'),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Aktualizovaný'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Zemepisná šírka'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Zemepisná dĺžka'),
        ),
    ]
