# Generated by Django 4.2.27 on 2026-02-08 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_route_updated_at_routestop_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated_at',
        ),
    ]
